//! Python model code generator.
//!
//! Generates dependency-free, strictly annotated Python dataclasses from a
//! `FileDescriptorSet`. The output preserves protobuf schema shape rather than
//! providing wire-format encode/decode.

use std::collections::HashMap;

use heck::{ToSnakeCase, ToUpperCamelCase};
use protoc_rs_schema::*;

use codegen_core::CodeWriter;

use crate::rust_gen::CodeGenError;

/// Generate Python code for all files in a `FileDescriptorSet`.
///
/// Returns a map from module path (e.g. `"my.package.py"`) to generated source.
pub fn generate_python(fds: &FileDescriptorSet) -> Result<HashMap<String, String>, CodeGenError> {
    let mut result: HashMap<String, String> = HashMap::new();
    for file in &fds.file {
        let filename = output_stem(file);
        let source = generate_file(file)?;
        if !source.trim().is_empty() {
            let key = format!("{filename}.py");
            result
                .entry(key)
                .and_modify(|existing| {
                    existing.push('\n');
                    existing.push_str(&source);
                })
                .or_insert(source);
        }
    }
    Ok(result)
}

fn output_stem(file: &FileDescriptorProto) -> String {
    let package = file.package.as_deref().unwrap_or("");
    if package.is_empty() {
        file.name
            .as_deref()
            .unwrap_or("unknown")
            .trim_end_matches(".proto")
            .replace('/', ".")
            .to_string()
    } else {
        package.to_string()
    }
}

fn generate_file(file: &FileDescriptorProto) -> Result<String, CodeGenError> {
    let syntax = file.syntax_enum();
    let package = file.package.as_deref().unwrap_or("");
    let mut gen = PythonGen {
        w: CodeWriter::new(),
        syntax,
        package: package.to_string(),
        nesting: Vec::new(),
    };

    gen.w.line("# This file is @generated by protoc-rs.");
    gen.w.line("from __future__ import annotations");
    gen.w.blank();
    gen.w.line("from dataclasses import dataclass, field");
    gen.w.line("from enum import IntEnum");
    gen.w.line("from typing import Literal");

    for e in &file.enum_type {
        gen.w.blank();
        gen.gen_enum(e)?;
    }

    for msg in &file.message_type {
        gen.w.blank();
        gen.gen_message(msg)?;
    }

    Ok(gen.w.finish())
}

struct PythonGen {
    w: CodeWriter,
    syntax: Syntax,
    package: String,
    nesting: Vec<String>,
}

impl PythonGen {
    fn current_fqn_prefix(&self) -> String {
        let mut parts = Vec::new();
        if !self.package.is_empty() {
            parts.push(self.package.clone());
        }
        parts.extend(self.nesting.iter().cloned());
        parts.join(".")
    }

    fn gen_message(&mut self, msg: &DescriptorProto) -> Result<(), CodeGenError> {
        let name = msg
            .name
            .as_deref()
            .ok_or(CodeGenError::MissingMessageName)?;
        if is_map_entry(msg) {
            return Ok(());
        }

        let py_name = to_upper_camel(name);
        let (regular_fields, oneof_groups) = partition_fields(msg);

        self.w.line("@dataclass(slots=True)");
        self.w.line(&format!("class {py_name}:"));
        self.w.indent();
        if regular_fields.is_empty() && oneof_groups.is_empty() {
            self.w.line("pass");
        } else {
            for field in &regular_fields {
                self.gen_field(field, msg)?;
            }
            for (oneof_idx, _) in &oneof_groups {
                let oneof = &msg.oneof_decl[*oneof_idx as usize];
                let oneof_name = oneof.name.as_deref().unwrap_or("unknown");
                let attr_name = to_snake(oneof_name);
                let type_name = format!("{py_name}{}", to_upper_camel(oneof_name));
                self.w
                    .line(&format!("{attr_name}: {type_name} | None = None"));
            }
        }
        self.w.dedent();

        self.nesting.push(name.to_string());

        for e in &msg.enum_type {
            self.w.blank();
            self.gen_enum(e)?;
        }

        for nested in &msg.nested_type {
            if !is_map_entry(nested) {
                self.w.blank();
                self.gen_message(nested)?;
            }
        }

        for (oneof_idx, fields) in &oneof_groups {
            let oneof = &msg.oneof_decl[*oneof_idx as usize];
            self.w.blank();
            self.gen_oneof_alias(&py_name, oneof, fields);
        }

        self.nesting.pop();
        Ok(())
    }

    fn gen_field(
        &mut self,
        field_desc: &FieldDescriptorProto,
        parent_msg: &DescriptorProto,
    ) -> Result<(), CodeGenError> {
        let name = field_desc
            .name
            .as_deref()
            .ok_or(CodeGenError::MissingFieldName)?;
        let attr_name = to_snake(name);

        if let Some((key_field, val_field)) = find_map_entry(field_desc, parent_msg) {
            let key_type = py_map_key_type(key_field.r#type.unwrap_or(FieldType::String));
            let val_type = self.py_field_base_type(val_field);
            self.w.line(&format!(
                "{attr_name}: dict[{key_type}, {val_type}] = field(default_factory=dict)"
            ));
            return Ok(());
        }

        let optional = self.is_field_optional(field_desc);
        let repeated = field_desc.label == Some(FieldLabel::Repeated);
        let base_type = self.py_field_base_type(field_desc);
        if repeated {
            self.w.line(&format!(
                "{attr_name}: list[{base_type}] = field(default_factory=list)"
            ));
        } else if optional {
            self.w
                .line(&format!("{attr_name}: {base_type} | None = None"));
        } else {
            let default = py_default_value(field_desc.r#type.unwrap_or(FieldType::Int32));
            self.w
                .line(&format!("{attr_name}: {base_type} = {default}"));
        }
        Ok(())
    }

    fn is_field_optional(&self, field: &FieldDescriptorProto) -> bool {
        let label = field.label.unwrap_or(FieldLabel::Optional);
        if label == FieldLabel::Repeated {
            return false;
        }
        if field.proto3_optional == Some(true) {
            return true;
        }
        let field_type = field.r#type.unwrap_or(FieldType::Int32);
        match self.syntax {
            Syntax::Proto3 => field_type == FieldType::Message,
            Syntax::Proto2 | Syntax::Unknown(_) => label != FieldLabel::Required,
        }
    }

    fn gen_enum(&mut self, e: &EnumDescriptorProto) -> Result<(), CodeGenError> {
        let name = e.name.as_deref().ok_or(CodeGenError::MissingEnumName)?;
        let py_name = to_upper_camel(name);
        let variants = enum_variants(e, name);

        self.w.line(&format!("class {py_name}(IntEnum):"));
        self.w.indent();
        if variants.is_empty() {
            self.w.line("pass");
        } else {
            for (_, number, variant) in variants {
                self.w.line(&format!("{variant} = {number}"));
            }
        }
        self.w.dedent();
        Ok(())
    }

    fn gen_oneof_alias(
        &mut self,
        parent_py_name: &str,
        oneof: &OneofDescriptorProto,
        fields: &[&FieldDescriptorProto],
    ) {
        let oneof_name = oneof.name.as_deref().unwrap_or("unknown");
        let alias_name = format!("{parent_py_name}{}", to_upper_camel(oneof_name));
        let variants: Vec<String> = fields
            .iter()
            .map(|field| {
                let field_name = field.name.as_deref().unwrap_or("unknown");
                format!("Literal[\"{}\"]", to_snake(field_name))
            })
            .collect();
        if variants.is_empty() {
            self.w.line(&format!("{alias_name} = None"));
        } else {
            self.w
                .line(&format!("{alias_name} = {}", variants.join(" | ")));
        }
    }

    fn py_field_base_type(&self, field: &FieldDescriptorProto) -> String {
        match field.r#type.unwrap_or(FieldType::Int32) {
            FieldType::Message => {
                let type_name = field.type_name.as_deref().unwrap_or("Unknown");
                fqn_to_py_type(type_name, &self.current_fqn_prefix())
            }
            FieldType::Enum => {
                let type_name = field.type_name.as_deref().unwrap_or("Unknown");
                fqn_to_py_type(type_name, &self.current_fqn_prefix())
            }
            ft => py_scalar_type(ft).to_string(),
        }
    }
}

fn partition_fields(
    msg: &DescriptorProto,
) -> (
    Vec<&FieldDescriptorProto>,
    Vec<(i32, Vec<&FieldDescriptorProto>)>,
) {
    let mut regular = Vec::new();
    let mut oneof_map: HashMap<i32, Vec<&FieldDescriptorProto>> = HashMap::new();

    for field in &msg.field {
        if field.proto3_optional == Some(true) {
            regular.push(field);
        } else if let Some(idx) = field.oneof_index {
            oneof_map.entry(idx).or_default().push(field);
        } else {
            regular.push(field);
        }
    }

    let mut oneof_groups: Vec<(i32, Vec<&FieldDescriptorProto>)> = oneof_map.into_iter().collect();
    oneof_groups.sort_by_key(|(idx, _)| *idx);
    (regular, oneof_groups)
}

fn is_map_entry(msg: &DescriptorProto) -> bool {
    msg.options
        .as_ref()
        .and_then(|o| o.map_entry)
        .unwrap_or(false)
}

fn find_map_entry<'a>(
    field: &FieldDescriptorProto,
    parent_msg: &'a DescriptorProto,
) -> Option<(&'a FieldDescriptorProto, &'a FieldDescriptorProto)> {
    if field.label != Some(FieldLabel::Repeated) || field.r#type != Some(FieldType::Message) {
        return None;
    }
    let short = field.type_name.as_deref()?.rsplit('.').next()?;
    for nested in &parent_msg.nested_type {
        if nested.name.as_deref() == Some(short) && is_map_entry(nested) {
            let key = nested.field.iter().find(|f| f.number == Some(1))?;
            let val = nested.field.iter().find(|f| f.number == Some(2))?;
            return Some((key, val));
        }
    }
    None
}

fn py_scalar_type(ft: FieldType) -> &'static str {
    match ft {
        FieldType::Double | FieldType::Float => "float",
        FieldType::Int64
        | FieldType::Uint64
        | FieldType::Int32
        | FieldType::Uint32
        | FieldType::Fixed64
        | FieldType::Fixed32
        | FieldType::Sfixed32
        | FieldType::Sfixed64
        | FieldType::Sint32
        | FieldType::Sint64
        | FieldType::Enum => "int",
        FieldType::Bool => "bool",
        FieldType::String => "str",
        FieldType::Bytes => "bytes",
        FieldType::Message | FieldType::Group => "object",
    }
}

fn py_map_key_type(ft: FieldType) -> &'static str {
    match ft {
        FieldType::String => "str",
        FieldType::Bool => "bool",
        FieldType::Int32
        | FieldType::Uint32
        | FieldType::Sint32
        | FieldType::Fixed32
        | FieldType::Sfixed32
        | FieldType::Int64
        | FieldType::Uint64
        | FieldType::Sint64
        | FieldType::Fixed64
        | FieldType::Sfixed64 => "int",
        _ => "str",
    }
}

fn py_default_value(ft: FieldType) -> &'static str {
    match ft {
        FieldType::Double | FieldType::Float => "0.0",
        FieldType::Bool => "False",
        FieldType::String => "\"\"",
        FieldType::Bytes => "b\"\"",
        FieldType::Message | FieldType::Group => "None",
        _ => "0",
    }
}

fn enum_variants(e: &EnumDescriptorProto, enum_name: &str) -> Vec<(String, i32, String)> {
    let mut seen_numbers = std::collections::HashSet::new();
    e.value
        .iter()
        .filter_map(|val| {
            let val_name = val.name.as_deref().unwrap_or("UNKNOWN");
            let number = val.number.unwrap_or(0);
            if !seen_numbers.insert(number) {
                return None;
            }
            let stripped = strip_enum_prefix(enum_name, val_name);
            Some((val_name.to_string(), number, to_enum_variant(&stripped)))
        })
        .collect()
}

fn strip_enum_prefix(enum_name: &str, value_name: &str) -> String {
    let prefix = enum_name.to_snake_case().to_uppercase();
    let stripped = if let Some(rest) = value_name.strip_prefix(&prefix) {
        rest.strip_prefix('_').unwrap_or(value_name)
    } else {
        value_name
    };
    if stripped.is_empty() {
        value_name.to_string()
    } else {
        stripped.to_string()
    }
}

fn fqn_to_py_type(fqn: &str, current_scope: &str) -> String {
    let stripped = fqn.strip_prefix('.').unwrap_or(fqn);
    let relative = if let Some(rest) = stripped.strip_prefix(current_scope) {
        rest.strip_prefix('.').unwrap_or(rest)
    } else {
        stripped
    };
    let parts: Vec<&str> = relative.split('.').filter(|p| !p.is_empty()).collect();
    parts
        .last()
        .map(|part| to_upper_camel(part))
        .unwrap_or_else(|| "Unknown".to_string())
}

fn to_snake(name: &str) -> String {
    sanitize_py_identifier(&name.to_snake_case())
}

fn to_upper_camel(name: &str) -> String {
    let s = name.to_upper_camel_case();
    if s.is_empty() {
        "Unknown".to_string()
    } else {
        sanitize_py_identifier(&s)
    }
}

fn to_enum_variant(name: &str) -> String {
    let variant = name.to_snake_case().to_uppercase();
    if variant.is_empty() {
        "UNKNOWN".to_string()
    } else {
        sanitize_py_identifier(&variant)
    }
}

fn sanitize_py_identifier(name: &str) -> String {
    match name {
        "False" | "None" | "True" | "and" | "as" | "assert" | "async" | "await" | "break"
        | "class" | "continue" | "def" | "del" | "elif" | "else" | "except" | "finally" | "for"
        | "from" | "global" | "if" | "import" | "in" | "is" | "lambda" | "nonlocal" | "not"
        | "or" | "pass" | "raise" | "return" | "try" | "while" | "with" | "yield" | "match"
        | "case" | "type" => format!("{name}_"),
        _ => name.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate(proto: &str, module: &str) -> String {
        let fds = protoc_rs_analyzer::analyze(proto).expect("analyze proto");
        let files = generate_python(&fds).expect("generate Python");
        files
            .get(&format!("{module}.py"))
            .unwrap_or_else(|| panic!("missing module {module}.py; got {:?}", files.keys()))
            .clone()
    }

    #[test]
    fn python_all_scalar_types() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_scalars;

                message AllScalars {
                    double f_double = 1;
                    float f_float = 2;
                    int32 f_int32 = 3;
                    int64 f_int64 = 4;
                    uint32 f_uint32 = 5;
                    uint64 f_uint64 = 6;
                    sint32 f_sint32 = 7;
                    sint64 f_sint64 = 8;
                    fixed32 f_fixed32 = 9;
                    fixed64 f_fixed64 = 10;
                    sfixed32 f_sfixed32 = 11;
                    sfixed64 f_sfixed64 = 12;
                    bool f_bool = 13;
                    string f_string = 14;
                    bytes f_bytes = 15;
                }
            "#,
            "test_scalars",
        );

        assert!(source.contains("@dataclass(slots=True)"));
        assert!(source.contains("class AllScalars:"));
        assert!(source.contains("f_double: float = 0.0"));
        assert!(source.contains("f_int64: int = 0"));
        assert!(source.contains("f_uint64: int = 0"));
        assert!(source.contains("f_bool: bool = False"));
        assert!(source.contains("f_string: str = \"\""));
        assert!(source.contains("f_bytes: bytes = b\"\""));
    }

    #[test]
    fn python_proto3_optional() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_optional;

                message WithOptional {
                    optional int32 opt_int = 1;
                    optional string opt_str = 2;
                    optional double opt_dbl = 3;
                    optional bool opt_bool = 4;
                    optional bytes opt_bytes = 5;
                }
            "#,
            "test_optional",
        );

        assert!(source.contains("opt_int: int | None = None"));
        assert!(source.contains("opt_str: str | None = None"));
        assert!(source.contains("opt_dbl: float | None = None"));
        assert!(source.contains("opt_bool: bool | None = None"));
        assert!(source.contains("opt_bytes: bytes | None = None"));
    }

    #[test]
    fn python_repeated_and_bytes() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_repeated;

                message WithRepeated {
                    repeated int32 ids = 1;
                    repeated string names = 2;
                    repeated bytes blobs = 3;
                    repeated double scores = 4;
                }
            "#,
            "test_repeated",
        );

        assert!(source.contains("ids: list[int] = field(default_factory=list)"));
        assert!(source.contains("names: list[str] = field(default_factory=list)"));
        assert!(source.contains("blobs: list[bytes] = field(default_factory=list)"));
        assert!(source.contains("scores: list[float] = field(default_factory=list)"));
    }

    #[test]
    fn python_enum_and_alias() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_enum;

                enum AliasedEnum {
                    option allow_alias = true;
                    ALIASED_ENUM_UNKNOWN = 0;
                    ALIASED_ENUM_FIRST = 1;
                    ALIASED_ENUM_SYNONYM = 1;
                    ALIASED_ENUM_SECOND = 2;
                }

                message WithEnum {
                    AliasedEnum value = 1;
                    repeated AliasedEnum values = 2;
                    optional AliasedEnum maybe_value = 3;
                }
            "#,
            "test_enum",
        );

        assert!(source.contains("class AliasedEnum(IntEnum):"));
        assert!(source.contains("UNKNOWN = 0"));
        assert!(source.contains("FIRST = 1"));
        assert!(!source.contains("SYNONYM = 1"));
        assert!(source.contains("value: AliasedEnum = 0"));
        assert!(source.contains("values: list[AliasedEnum] = field(default_factory=list)"));
        assert!(source.contains("maybe_value: AliasedEnum | None = None"));
    }

    #[test]
    fn python_oneof_generation() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_oneof;

                message WithOneof {
                    string common = 1;
                    oneof payload {
                        string text = 2;
                        int32 number = 3;
                        bool flag = 4;
                        bytes data = 5;
                    }
                }
            "#,
            "test_oneof",
        );

        assert!(source.contains("payload: WithOneofPayload | None = None"));
        assert!(source.contains(
            "WithOneofPayload = Literal[\"text\"] | Literal[\"number\"] | Literal[\"flag\"] | Literal[\"data\"]"
        ));
    }

    #[test]
    fn python_nested_message() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_nested;

                message Outer {
                    message Inner {
                        int32 value = 1;
                        string label = 2;
                    }
                    Inner inner = 1;
                    repeated Inner items = 2;
                    optional Inner maybe = 3;
                }
            "#,
            "test_nested",
        );

        assert!(source.contains("class Outer:"));
        assert!(source.contains("class Inner:"));
        assert!(source.contains("inner: Inner | None = None"));
        assert!(source.contains("items: list[Inner] = field(default_factory=list)"));
        assert!(source.contains("maybe: Inner | None = None"));
    }

    #[test]
    fn python_map_fields() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_maps;

                enum Priority {
                    PRIORITY_UNKNOWN = 0;
                    PRIORITY_LOW = 1;
                    PRIORITY_HIGH = 2;
                }

                message WithMaps {
                    map<string, string> str_map = 1;
                    map<int32, string> int_map = 2;
                    map<string, int64> val_map = 3;
                    map<string, bool> bool_map = 4;
                    map<string, Priority> priorities = 5;
                }
            "#,
            "test_maps",
        );

        assert!(source.contains("str_map: dict[str, str] = field(default_factory=dict)"));
        assert!(source.contains("int_map: dict[int, str] = field(default_factory=dict)"));
        assert!(source.contains("val_map: dict[str, int] = field(default_factory=dict)"));
        assert!(source.contains("bool_map: dict[str, bool] = field(default_factory=dict)"));
        assert!(source.contains("priorities: dict[str, Priority] = field(default_factory=dict)"));
        assert!(!source.contains("StrMapEntry"));
    }

    #[test]
    fn python_keyword_fields() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_keywords;

                message Keywords {
                    string type = 1;
                    int32 class = 2;
                    bool match = 3;
                    string from = 4;
                }
            "#,
            "test_keywords",
        );

        assert!(source.contains("type_: str = \"\""));
        assert!(source.contains("class_: int = 0"));
        assert!(source.contains("match_: bool = False"));
        assert!(source.contains("from_: str = \"\""));
    }

    #[test]
    fn python_proto2_optional_required() {
        let source = generate(
            r#"
                syntax = "proto2";
                package test_proto2;

                message Proto2Msg {
                    optional int32 opt_field = 1;
                    required string req_field = 2;
                    repeated int32 rep_field = 3;
                    optional bool opt_bool = 4;
                }
            "#,
            "test_proto2",
        );

        assert!(source.contains("opt_field: int | None = None"));
        assert!(source.contains("req_field: str = \"\""));
        assert!(source.contains("rep_field: list[int] = field(default_factory=list)"));
        assert!(source.contains("opt_bool: bool | None = None"));
    }

    #[test]
    fn python_complex_combined() {
        let source = generate(
            r#"
                syntax = "proto3";
                package test_complex;

                enum Status {
                    STATUS_UNKNOWN = 0;
                    STATUS_ACTIVE = 1;
                    STATUS_INACTIVE = 2;
                }

                message Person {
                    string name = 1;
                    int32 id = 2;
                    string email = 3;
                    Status status = 4;
                    repeated string tags = 5;
                    optional double score = 6;

                    message Address {
                        string street = 1;
                        string city = 2;
                        int32 zip = 3;
                    }

                    Address home_address = 7;
                    map<string, string> metadata = 8;

                    oneof contact {
                        string phone = 9;
                        string fax = 10;
                    }

                    repeated Address other_addresses = 11;
                }
            "#,
            "test_complex",
        );

        assert!(source.contains("class Status(IntEnum):"));
        assert!(source.contains("class Person:"));
        assert!(source.contains("tags: list[str] = field(default_factory=list)"));
        assert!(source.contains("score: float | None = None"));
        assert!(source.contains("class Address:"));
        assert!(source.contains("home_address: Address | None = None"));
        assert!(source.contains("metadata: dict[str, str] = field(default_factory=dict)"));
        assert!(source.contains("contact: PersonContact | None = None"));
        assert!(source.contains("other_addresses: list[Address] = field(default_factory=list)"));
    }
}
