//! Prost-compatible Rust code generator.
//!
//! Generates Rust structs and enums from a `FileDescriptorSet` that are compatible
//! with `prost`'s derive macros (`::prost::Message`, `::prost::Enumeration`, `::prost::Oneof`).

use std::collections::HashMap;

use heck::{ToSnakeCase, ToUpperCamelCase};
use protoc_rs_schema::*;

/// Generate Rust code for all files in a `FileDescriptorSet`.
///
/// Returns a map from module path (e.g. `"my.package"`) to generated Rust source code.
/// Files without a package use an empty string key.
pub fn generate_rust(
    fds: &FileDescriptorSet,
) -> Result<HashMap<String, String>, CodeGenError> {
    let mut result = HashMap::new();
    for file in &fds.file {
        let package = file.package.as_deref().unwrap_or("");
        let filename = if package.is_empty() {
            // Use the proto filename (sans .proto) as the module name
            file.name
                .as_deref()
                .unwrap_or("unknown")
                .trim_end_matches(".proto")
                .replace('/', ".")
                .to_string()
        } else {
            package.to_string()
        };
        let source = generate_file(file)?;
        if !source.trim().is_empty() {
            result.insert(format!("{filename}.rs"), source);
        }
    }
    Ok(result)
}

/// Generate Rust code for a single file.
fn generate_file(file: &FileDescriptorProto) -> Result<String, CodeGenError> {
    let syntax = file.syntax_enum();
    let package = file.package.as_deref().unwrap_or("");
    let mut gen = RustGen {
        buf: String::new(),
        indent: 0,
        syntax: syntax.clone(),
        package: package.to_string(),
        nesting: Vec::new(),
    };

    gen.push_line("// This file is @generated by protoc-rs.");

    // Messages first (matches prost ordering)
    for msg in &file.message_type {
        gen.gen_message(msg)?;
        gen.push_line("");
    }

    // Top-level enums
    for e in &file.enum_type {
        gen.gen_enum(e)?;
        gen.push_line("");
    }

    Ok(gen.buf)
}

#[derive(Debug)]
pub enum CodeGenError {
    MissingFieldName,
    MissingMessageName,
    MissingEnumName,
}

impl std::fmt::Display for CodeGenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingFieldName => write!(f, "missing field name in message"),
            Self::MissingMessageName => write!(f, "missing message name"),
            Self::MissingEnumName => write!(f, "missing enum name"),
        }
    }
}

impl std::error::Error for CodeGenError {}

// ---------------------------------------------------------------------------
// Generator state
// ---------------------------------------------------------------------------

struct RustGen {
    buf: String,
    indent: u32,
    syntax: Syntax,
    package: String,
    /// Current nesting path of message names (e.g., ["Outer", "Inner"]).
    /// Used to produce relative type paths for nested references.
    nesting: Vec<String>,
}

impl RustGen {
    fn push_indent(&mut self) {
        for _ in 0..self.indent {
            self.buf.push_str("    ");
        }
    }

    fn push_line(&mut self, line: &str) {
        if line.is_empty() {
            self.buf.push('\n');
        } else {
            self.push_indent();
            self.buf.push_str(line);
            self.buf.push('\n');
        }
    }

    // -----------------------------------------------------------------------
    // Message generation
    // -----------------------------------------------------------------------

    /// Build the fully-qualified prefix for the current scope (package + nesting).
    /// E.g., with package "test" and nesting ["Outer"], returns "test.Outer".
    fn current_fqn_prefix(&self) -> String {
        let mut parts = Vec::new();
        if !self.package.is_empty() {
            parts.push(self.package.clone());
        }
        parts.extend(self.nesting.iter().cloned());
        parts.join(".")
    }

    fn gen_message(&mut self, msg: &DescriptorProto) -> Result<(), CodeGenError> {
        let name = msg
            .name
            .as_deref()
            .ok_or(CodeGenError::MissingMessageName)?;
        let rust_name = to_upper_camel(name);

        // Skip map entry types -- they are inlined into the parent field
        if is_map_entry(msg) {
            return Ok(());
        }

        // Partition fields: regular vs oneof members
        let (regular_fields, oneof_groups) = partition_fields(msg);

        // Emit struct
        self.push_line("#[derive(Clone, PartialEq, ::prost::Message)]");
        self.push_line(&format!("pub struct {rust_name} {{"));
        self.indent += 1;

        // Regular fields
        for field in &regular_fields {
            self.gen_field(field, msg)?;
        }

        // Oneof fields
        let mod_name = to_snake(name);
        for (oneof_idx, fields) in &oneof_groups {
            let oneof_decl = &msg.oneof_decl[*oneof_idx as usize];
            let oneof_name = oneof_decl.name.as_deref().unwrap_or("unknown");
            let oneof_rust_name = to_snake(oneof_name);
            let oneof_type_name = to_upper_camel(oneof_name);

            // Collect tags
            let tags: Vec<String> = fields
                .iter()
                .filter_map(|f| f.number.map(|n| format!("{n}")))
                .collect();
            let tags_str = tags.join(", ");

            self.push_line(&format!(
                "#[prost(oneof = \"{mod_name}::{oneof_type_name}\", tags = \"{tags_str}\")]"
            ));
            self.push_line(&format!(
                "pub {oneof_rust_name}: ::core::option::Option<{mod_name}::{oneof_type_name}>,"
            ));
        }

        self.indent -= 1;
        self.push_line("}");

        // Nested mod for nested types, enums, and oneof enums
        let has_nested = !msg.nested_type.iter().all(|m| is_map_entry(m))
            || !msg.enum_type.is_empty()
            || !oneof_groups.is_empty();

        if has_nested {
            // Push nesting for the mod scope -- type refs inside nested
            // messages will be relative to this message's scope.
            self.nesting.push(name.to_string());

            self.push_line(&format!("pub mod {mod_name} {{"));
            self.indent += 1;

            // Nested enums
            for e in &msg.enum_type {
                self.gen_enum(e)?;
                self.push_line("");
            }

            // Nested messages (skip map entries)
            for nested in &msg.nested_type {
                if !is_map_entry(nested) {
                    self.gen_message(nested)?;
                    self.push_line("");
                }
            }

            // Oneof enums
            for (oneof_idx, fields) in &oneof_groups {
                let oneof_decl = &msg.oneof_decl[*oneof_idx as usize];
                self.gen_oneof_enum(oneof_decl, fields, msg)?;
                self.push_line("");
            }

            self.indent -= 1;
            self.push_line("}");

            self.nesting.pop();
        }

        Ok(())
    }

    fn gen_field(
        &mut self,
        field: &FieldDescriptorProto,
        parent_msg: &DescriptorProto,
    ) -> Result<(), CodeGenError> {
        let name = field.name.as_deref().ok_or(CodeGenError::MissingFieldName)?;
        let tag = field.number.unwrap_or(0);
        let rust_name = to_snake(name);
        let label = field.label.unwrap_or(FieldLabel::Optional);

        // Check if this is a map field
        if let Some((key_field, val_field)) = find_map_entry(field, parent_msg) {
            let key_tag = prost_type_tag(key_field.r#type.unwrap_or(FieldType::Int32));
            let val_tag = prost_type_tag_for_map_value(&val_field, &self.current_fqn_prefix());
            self.push_line(&format!(
                "#[prost(map = \"{key_tag}, {val_tag}\", tag = \"{tag}\")]"
            ));
            let key_type = rust_type(key_field.r#type.unwrap_or(FieldType::Int32));
            let val_type = rust_map_value_type(&val_field, &self.current_fqn_prefix());
            self.push_line(&format!(
                "pub {rust_name}: ::std::collections::HashMap<{key_type}, {val_type}>,"
            ));
            return Ok(());
        }

        // Determine wrapping (Option, Vec, or bare)
        let is_repeated = label == FieldLabel::Repeated;
        let is_optional = self.is_field_optional(field);

        // Build prost annotation
        let type_tag = prost_field_tag(field, &self.current_fqn_prefix());
        let is_required = label == FieldLabel::Required;
        let mut prost_parts = vec![type_tag];
        if is_optional {
            prost_parts.push("optional".to_string());
        }
        if is_required {
            prost_parts.push("required".to_string());
        }
        if is_repeated {
            prost_parts.push("repeated".to_string());
            // Proto2 repeated scalar fields are not packed by default
            if matches!(self.syntax, Syntax::Proto2) && is_packable_type(field) {
                prost_parts.push("packed = \"false\"".to_string());
            }
        }
        prost_parts.push(format!("tag = \"{tag}\""));
        let prost_attr = prost_parts.join(", ");

        self.push_line(&format!("#[prost({prost_attr})]"));

        // Build Rust type
        let base_type = rust_field_type(field, &self.current_fqn_prefix());
        let full_type = if is_repeated {
            format!("::prost::alloc::vec::Vec<{base_type}>")
        } else if is_optional {
            format!("::core::option::Option<{base_type}>")
        } else {
            base_type
        };

        self.push_line(&format!("pub {rust_name}: {full_type},"));
        Ok(())
    }

    fn is_field_optional(&self, field: &FieldDescriptorProto) -> bool {
        let label = field.label.unwrap_or(FieldLabel::Optional);
        if label == FieldLabel::Repeated {
            return false;
        }
        if field.proto3_optional == Some(true) {
            return true;
        }
        let field_type = field.r#type.unwrap_or(FieldType::Int32);
        match &self.syntax {
            Syntax::Proto3 => {
                // Proto3: only message fields are optional by default
                field_type == FieldType::Message
            }
            Syntax::Proto2 | Syntax::Unknown(_) => {
                // Proto2: optional fields are Optional, required are bare
                label != FieldLabel::Required
            }
        }
    }

    // -----------------------------------------------------------------------
    // Enum generation
    // -----------------------------------------------------------------------

    fn gen_enum(&mut self, e: &EnumDescriptorProto) -> Result<(), CodeGenError> {
        let name = e.name.as_deref().ok_or(CodeGenError::MissingEnumName)?;
        let rust_name = to_upper_camel(name);

        self.push_line(
            "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]",
        );
        self.push_line("#[repr(i32)]");
        self.push_line(&format!("pub enum {rust_name} {{"));
        self.indent += 1;

        // Track seen numbers for allow_alias dedup
        let mut seen_numbers = std::collections::HashSet::new();
        for val in &e.value {
            let val_name = val.name.as_deref().unwrap_or("UNKNOWN");
            let number = val.number.unwrap_or(0);
            if !seen_numbers.insert(number) {
                continue; // Skip aliased values
            }
            let stripped = strip_enum_prefix(name, val_name);
            let rust_variant = to_upper_camel(&stripped);
            self.push_line(&format!("{rust_variant} = {number},"));
        }

        self.indent -= 1;
        self.push_line("}");

        // impl as_str_name / from_str_name
        self.push_line(&format!("impl {rust_name} {{"));
        self.indent += 1;

        self.push_line("pub fn as_str_name(&self) -> &'static str {");
        self.indent += 1;
        self.push_line("match self {");
        self.indent += 1;
        seen_numbers.clear();
        for val in &e.value {
            let val_name = val.name.as_deref().unwrap_or("UNKNOWN");
            let number = val.number.unwrap_or(0);
            if !seen_numbers.insert(number) {
                continue;
            }
            let stripped = strip_enum_prefix(name, val_name);
            let rust_variant = to_upper_camel(&stripped);
            self.push_line(&format!(
                "Self::{rust_variant} => \"{val_name}\","
            ));
        }
        self.indent -= 1;
        self.push_line("}");
        self.indent -= 1;
        self.push_line("}");

        self.push_line("pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {");
        self.indent += 1;
        self.push_line("match value {");
        self.indent += 1;
        seen_numbers.clear();
        for val in &e.value {
            let val_name = val.name.as_deref().unwrap_or("UNKNOWN");
            let number = val.number.unwrap_or(0);
            if !seen_numbers.insert(number) {
                continue;
            }
            let stripped = strip_enum_prefix(name, val_name);
            let rust_variant = to_upper_camel(&stripped);
            self.push_line(&format!(
                "\"{val_name}\" => Some(Self::{rust_variant}),"
            ));
        }
        self.push_line("_ => None,");
        self.indent -= 1;
        self.push_line("}");
        self.indent -= 1;
        self.push_line("}");

        self.indent -= 1;
        self.push_line("}");

        Ok(())
    }

    // -----------------------------------------------------------------------
    // Oneof enum generation
    // -----------------------------------------------------------------------

    fn gen_oneof_enum(
        &mut self,
        oneof: &OneofDescriptorProto,
        fields: &[&FieldDescriptorProto],
        _parent_msg: &DescriptorProto,
    ) -> Result<(), CodeGenError> {
        let oneof_name = oneof.name.as_deref().unwrap_or("unknown");
        let rust_name = to_upper_camel(oneof_name);

        self.push_line("#[derive(Clone, PartialEq, ::prost::Oneof)]");
        self.push_line(&format!("pub enum {rust_name} {{"));
        self.indent += 1;

        for field in fields {
            let field_name = field.name.as_deref().unwrap_or("unknown");
            let tag = field.number.unwrap_or(0);
            let type_tag = prost_field_tag(field, &self.current_fqn_prefix());

            self.push_line(&format!("#[prost({type_tag}, tag = \"{tag}\")]"));
            let variant_name = to_upper_camel(field_name);
            let base_type = rust_field_type(field, &self.current_fqn_prefix());

            let field_type = field.r#type.unwrap_or(FieldType::Int32);
            if field_type == FieldType::Message {
                self.push_line(&format!(
                    "{variant_name}(::prost::alloc::boxed::Box<{base_type}>),"
                ));
            } else {
                self.push_line(&format!("{variant_name}({base_type}),"));
            }
        }

        self.indent -= 1;
        self.push_line("}");

        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Field partitioning
// ---------------------------------------------------------------------------

/// Partition fields into regular fields and oneof groups.
/// Proto3 optional fields (with synthetic oneofs) are treated as regular fields.
fn partition_fields<'a>(
    msg: &'a DescriptorProto,
) -> (Vec<&'a FieldDescriptorProto>, Vec<(i32, Vec<&'a FieldDescriptorProto>)>) {
    let mut regular = Vec::new();
    let mut oneof_map: HashMap<i32, Vec<&FieldDescriptorProto>> = HashMap::new();

    for field in &msg.field {
        if field.proto3_optional == Some(true) {
            // Proto3 optional: treat as regular field (not oneof)
            regular.push(field);
        } else if let Some(idx) = field.oneof_index {
            oneof_map.entry(idx).or_default().push(field);
        } else {
            regular.push(field);
        }
    }

    let mut oneof_groups: Vec<(i32, Vec<&FieldDescriptorProto>)> =
        oneof_map.into_iter().collect();
    oneof_groups.sort_by_key(|(idx, _)| *idx);

    (regular, oneof_groups)
}

// ---------------------------------------------------------------------------
// Map field detection
// ---------------------------------------------------------------------------

/// Returns true if the field type supports packed encoding (numeric types, bools, enums).
fn is_packable_type(field: &FieldDescriptorProto) -> bool {
    matches!(
        field.r#type,
        Some(
            FieldType::Double
                | FieldType::Float
                | FieldType::Int64
                | FieldType::Uint64
                | FieldType::Int32
                | FieldType::Fixed64
                | FieldType::Fixed32
                | FieldType::Bool
                | FieldType::Uint32
                | FieldType::Sfixed32
                | FieldType::Sfixed64
                | FieldType::Sint32
                | FieldType::Sint64
                | FieldType::Enum
        )
    )
}

fn is_map_entry(msg: &DescriptorProto) -> bool {
    msg.options
        .as_ref()
        .and_then(|o| o.map_entry)
        .unwrap_or(false)
}

/// If this field is a map field, return (key_field, value_field) from the map entry type.
fn find_map_entry<'a>(
    field: &FieldDescriptorProto,
    parent_msg: &'a DescriptorProto,
) -> Option<(&'a FieldDescriptorProto, &'a FieldDescriptorProto)> {
    if field.label != Some(FieldLabel::Repeated) {
        return None;
    }
    if field.r#type != Some(FieldType::Message) {
        return None;
    }
    let type_name = field.type_name.as_deref()?;
    let short = type_name.rsplit('.').next()?;

    for nested in &parent_msg.nested_type {
        if nested.name.as_deref() == Some(short) && is_map_entry(nested) {
            let key = nested.field.iter().find(|f| f.number == Some(1))?;
            let val = nested.field.iter().find(|f| f.number == Some(2))?;
            return Some((key, val));
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

/// Prost annotation type tag for a field (e.g. "int32", "string", "message", "enumeration=...").
fn prost_field_tag(field: &FieldDescriptorProto, package: &str) -> String {
    let field_type = field.r#type.unwrap_or(FieldType::Int32);
    match field_type {
        FieldType::Enum => {
            let type_name = field.type_name.as_deref().unwrap_or("");
            let rust_path = fqn_to_rust_path(type_name, package);
            format!("enumeration = \"{rust_path}\"")
        }
        FieldType::Message => "message".to_string(),
        _ => prost_type_tag(field_type).to_string(),
    }
}

/// Prost type tag string for a scalar type.
fn prost_type_tag(ft: FieldType) -> &'static str {
    match ft {
        FieldType::Double => "double",
        FieldType::Float => "float",
        FieldType::Int64 => "int64",
        FieldType::Uint64 => "uint64",
        FieldType::Int32 => "int32",
        FieldType::Fixed64 => "fixed64",
        FieldType::Fixed32 => "fixed32",
        FieldType::Bool => "bool",
        FieldType::String => "string",
        FieldType::Bytes => "bytes = \"vec\"",
        FieldType::Uint32 => "uint32",
        FieldType::Sfixed32 => "sfixed32",
        FieldType::Sfixed64 => "sfixed64",
        FieldType::Sint32 => "sint32",
        FieldType::Sint64 => "sint64",
        FieldType::Enum => "int32", // fallback
        FieldType::Message | FieldType::Group => "message",
    }
}

fn prost_type_tag_for_map_value(field: &FieldDescriptorProto, package: &str) -> String {
    let ft = field.r#type.unwrap_or(FieldType::Int32);
    match ft {
        FieldType::Enum => {
            let type_name = field.type_name.as_deref().unwrap_or("");
            let rust_path = fqn_to_rust_path(type_name, package);
            format!("enumeration({rust_path})")
        }
        _ => prost_type_tag(ft).to_string(),
    }
}

/// Rust type for a field.
fn rust_field_type(field: &FieldDescriptorProto, package: &str) -> String {
    let ft = field.r#type.unwrap_or(FieldType::Int32);
    match ft {
        FieldType::Message => {
            let type_name = field.type_name.as_deref().unwrap_or("Unknown");
            fqn_to_rust_path(type_name, package)
        }
        FieldType::Enum => "i32".to_string(),
        _ => rust_type(ft).to_string(),
    }
}

/// Rust type for a map value field.
fn rust_map_value_type(field: &FieldDescriptorProto, package: &str) -> String {
    let ft = field.r#type.unwrap_or(FieldType::Int32);
    match ft {
        FieldType::Message => {
            let type_name = field.type_name.as_deref().unwrap_or("Unknown");
            fqn_to_rust_path(type_name, package)
        }
        FieldType::Enum => "i32".to_string(),
        _ => rust_type(ft).to_string(),
    }
}

/// Rust type for a scalar FieldType.
fn rust_type(ft: FieldType) -> &'static str {
    match ft {
        FieldType::Double => "f64",
        FieldType::Float => "f32",
        FieldType::Int64 | FieldType::Sfixed64 | FieldType::Sint64 => "i64",
        FieldType::Uint64 | FieldType::Fixed64 => "u64",
        FieldType::Int32 | FieldType::Sfixed32 | FieldType::Sint32 | FieldType::Enum => "i32",
        FieldType::Uint32 | FieldType::Fixed32 => "u32",
        FieldType::Bool => "bool",
        FieldType::String => "::prost::alloc::string::String",
        FieldType::Bytes => "::prost::alloc::vec::Vec<u8>",
        FieldType::Message | FieldType::Group => "Unknown",
    }
}

// ---------------------------------------------------------------------------
// Naming utilities
// ---------------------------------------------------------------------------

/// Convert to snake_case, handling Rust keywords.
fn to_snake(name: &str) -> String {
    let s = name.to_snake_case();
    sanitize_keyword(&s)
}

/// Convert to UpperCamelCase.
fn to_upper_camel(name: &str) -> String {
    let s = name.to_upper_camel_case();
    if s.is_empty() {
        "Unknown".to_string()
    } else {
        s
    }
}

/// Sanitize Rust keywords in field names.
/// Uses trailing underscore for `self`/`super` (cannot use `r#` for these),
/// and `r#` prefix for all other keywords (matching prost behavior).
fn sanitize_keyword(name: &str) -> String {
    match name {
        // self/super cannot use r# syntax in all positions
        "self" | "super" => format!("{name}_"),
        "as" | "break" | "const" | "continue" | "crate" | "else" | "enum" | "extern" | "false"
        | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move"
        | "mut" | "pub" | "ref" | "return" | "Self" | "static" | "struct"
        | "trait" | "true" | "type" | "unsafe" | "use" | "where" | "while" | "async"
        | "await" | "dyn" | "abstract" | "become" | "box" | "do" | "final" | "macro"
        | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield" | "try" => {
            format!("r#{name}")
        }
        _ => name.to_string(),
    }
}

/// Strip the common enum prefix from a value name.
///
/// E.g., strip_enum_prefix("Status", "STATUS_ACTIVE") -> "ACTIVE"
/// E.g., strip_enum_prefix("Color", "RED") -> "RED" (no prefix match)
fn strip_enum_prefix(enum_name: &str, value_name: &str) -> String {
    let prefix = enum_name.to_snake_case().to_uppercase();
    let stripped = if value_name.starts_with(&prefix) {
        let rest = &value_name[prefix.len()..];
        if rest.starts_with('_') {
            &rest[1..]
        } else {
            value_name
        }
    } else {
        value_name
    };
    if stripped.is_empty() {
        value_name.to_string()
    } else {
        stripped.to_string()
    }
}

/// Convert a fully-qualified proto type name to a Rust module path.
///
/// Strips the current package prefix to produce relative paths (matching prost behavior).
/// E.g. with package "example": ".example.Outer.Inner" -> "outer::Inner"
fn fqn_to_rust_path(fqn: &str, current_package: &str) -> String {
    let stripped = fqn.strip_prefix('.').unwrap_or(fqn);

    // Strip the current package prefix to produce relative paths
    let relative = if !current_package.is_empty() && stripped.starts_with(current_package) {
        let rest = &stripped[current_package.len()..];
        if rest.starts_with('.') {
            &rest[1..]
        } else if rest.is_empty() {
            rest
        } else {
            stripped // Package name is a prefix of a longer name, don't strip
        }
    } else {
        stripped
    };

    let parts: Vec<&str> = relative.split('.').collect();
    if parts.is_empty() || (parts.len() == 1 && parts[0].is_empty()) {
        return "Unknown".to_string();
    }

    // Last component is the type name (UpperCamel), everything before is package/nesting
    let mut rust_parts = Vec::new();
    for (i, part) in parts.iter().enumerate() {
        if i == parts.len() - 1 {
            rust_parts.push(to_upper_camel(part));
        } else {
            rust_parts.push(to_snake(part));
        }
    }

    if rust_parts.len() == 1 {
        return rust_parts[0].clone();
    }

    rust_parts.join("::")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strip_enum_prefix() {
        assert_eq!(strip_enum_prefix("Status", "STATUS_ACTIVE"), "ACTIVE");
        assert_eq!(strip_enum_prefix("Status", "STATUS_UNKNOWN"), "UNKNOWN");
        assert_eq!(strip_enum_prefix("Color", "RED"), "RED");
        assert_eq!(strip_enum_prefix("Color", "COLOR_RED"), "RED");
    }

    #[test]
    fn test_to_snake() {
        assert_eq!(to_snake("fieldName"), "field_name");
        assert_eq!(to_snake("type"), "r#type");
        assert_eq!(to_snake("MyField"), "my_field");
    }

    #[test]
    fn test_to_upper_camel() {
        assert_eq!(to_upper_camel("my_message"), "MyMessage");
        assert_eq!(to_upper_camel("UNKNOWN"), "Unknown");
        assert_eq!(to_upper_camel("active"), "Active");
    }

    #[test]
    fn test_fqn_to_rust_path() {
        // With matching package, prefix is stripped
        assert_eq!(fqn_to_rust_path(".test.Person", "test"), "Person");
        assert_eq!(
            fqn_to_rust_path(".test.Outer.Inner", "test"),
            "outer::Inner"
        );
        // Without package, full path preserved
        assert_eq!(fqn_to_rust_path(".Foo", ""), "Foo");
        // Cross-package reference keeps prefix
        assert_eq!(
            fqn_to_rust_path(".other.Thing", "test"),
            "other::Thing"
        );
    }

    #[test]
    fn test_simple_proto3_message() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto3".to_string()),
                message_type: vec![DescriptorProto {
                    name: Some("Person".to_string()),
                    field: vec![
                        FieldDescriptorProto {
                            name: Some("name".to_string()),
                            number: Some(1),
                            label: Some(FieldLabel::Optional),
                            r#type: Some(FieldType::String),
                            ..Default::default()
                        },
                        FieldDescriptorProto {
                            name: Some("id".to_string()),
                            number: Some(2),
                            label: Some(FieldLabel::Optional),
                            r#type: Some(FieldType::Int32),
                            ..Default::default()
                        },
                        FieldDescriptorProto {
                            name: Some("is_active".to_string()),
                            number: Some(3),
                            label: Some(FieldLabel::Optional),
                            r#type: Some(FieldType::Bool),
                            ..Default::default()
                        },
                    ],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];

        // Proto3 scalar fields should NOT be wrapped in Option
        assert!(source.contains("pub name: ::prost::alloc::string::String,"));
        assert!(source.contains("pub id: i32,"));
        assert!(source.contains("pub is_active: bool,"));
        assert!(source.contains("#[derive(Clone, PartialEq, ::prost::Message)]"));
        assert!(source.contains("pub struct Person"));
    }

    #[test]
    fn test_proto3_optional() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto3".to_string()),
                message_type: vec![DescriptorProto {
                    name: Some("Msg".to_string()),
                    field: vec![FieldDescriptorProto {
                        name: Some("maybe_id".to_string()),
                        number: Some(1),
                        label: Some(FieldLabel::Optional),
                        r#type: Some(FieldType::Int32),
                        proto3_optional: Some(true),
                        oneof_index: Some(0),
                        ..Default::default()
                    }],
                    oneof_decl: vec![OneofDescriptorProto {
                        name: Some("_maybe_id".to_string()),
                        ..Default::default()
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];

        // Proto3 optional should be Option<i32>, treated as regular field
        assert!(source.contains("optional"));
        assert!(source.contains("::core::option::Option<i32>"));
        // Should NOT generate a oneof enum for the synthetic oneof
    }

    #[test]
    fn test_repeated_field() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto3".to_string()),
                message_type: vec![DescriptorProto {
                    name: Some("Msg".to_string()),
                    field: vec![FieldDescriptorProto {
                        name: Some("items".to_string()),
                        number: Some(1),
                        label: Some(FieldLabel::Repeated),
                        r#type: Some(FieldType::Int32),
                        ..Default::default()
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];
        assert!(source.contains("::prost::alloc::vec::Vec<i32>"));
        assert!(source.contains("repeated"));
    }

    #[test]
    fn test_enum_generation() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto3".to_string()),
                enum_type: vec![EnumDescriptorProto {
                    name: Some("Status".to_string()),
                    value: vec![
                        EnumValueDescriptorProto {
                            name: Some("STATUS_UNKNOWN".to_string()),
                            number: Some(0),
                            ..Default::default()
                        },
                        EnumValueDescriptorProto {
                            name: Some("STATUS_ACTIVE".to_string()),
                            number: Some(1),
                            ..Default::default()
                        },
                    ],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];
        assert!(source.contains("::prost::Enumeration"));
        assert!(source.contains("#[repr(i32)]"));
        assert!(source.contains("Unknown = 0,"));
        assert!(source.contains("Active = 1,"));
        assert!(source.contains("as_str_name"));
        assert!(source.contains("from_str_name"));
    }

    #[test]
    fn test_oneof_generation() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto3".to_string()),
                message_type: vec![DescriptorProto {
                    name: Some("Msg".to_string()),
                    field: vec![
                        FieldDescriptorProto {
                            name: Some("text".to_string()),
                            number: Some(1),
                            label: Some(FieldLabel::Optional),
                            r#type: Some(FieldType::String),
                            oneof_index: Some(0),
                            ..Default::default()
                        },
                        FieldDescriptorProto {
                            name: Some("number".to_string()),
                            number: Some(2),
                            label: Some(FieldLabel::Optional),
                            r#type: Some(FieldType::Int32),
                            oneof_index: Some(0),
                            ..Default::default()
                        },
                    ],
                    oneof_decl: vec![OneofDescriptorProto {
                        name: Some("content".to_string()),
                        ..Default::default()
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];
        assert!(source.contains("::prost::Oneof"));
        assert!(source.contains("pub enum Content"));
        assert!(source.contains("Text(::prost::alloc::string::String)"));
        assert!(source.contains("Number(i32)"));
        assert!(source.contains("pub content: ::core::option::Option<msg::Content>"));
    }

    #[test]
    fn test_nested_message() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto3".to_string()),
                message_type: vec![DescriptorProto {
                    name: Some("Outer".to_string()),
                    field: vec![FieldDescriptorProto {
                        name: Some("inner".to_string()),
                        number: Some(1),
                        label: Some(FieldLabel::Optional),
                        r#type: Some(FieldType::Message),
                        type_name: Some(".test.Outer.Inner".to_string()),
                        ..Default::default()
                    }],
                    nested_type: vec![DescriptorProto {
                        name: Some("Inner".to_string()),
                        field: vec![FieldDescriptorProto {
                            name: Some("value".to_string()),
                            number: Some(1),
                            label: Some(FieldLabel::Optional),
                            r#type: Some(FieldType::Int32),
                            ..Default::default()
                        }],
                        ..Default::default()
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];
        assert!(source.contains("pub struct Outer"));
        assert!(source.contains("pub mod outer"));
        assert!(source.contains("pub struct Inner"));
        assert!(source.contains("pub inner: ::core::option::Option<outer::Inner>"));
    }

    #[test]
    fn test_map_field() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto3".to_string()),
                message_type: vec![DescriptorProto {
                    name: Some("Msg".to_string()),
                    field: vec![FieldDescriptorProto {
                        name: Some("metadata".to_string()),
                        number: Some(1),
                        label: Some(FieldLabel::Repeated),
                        r#type: Some(FieldType::Message),
                        type_name: Some(".test.Msg.MetadataEntry".to_string()),
                        ..Default::default()
                    }],
                    nested_type: vec![DescriptorProto {
                        name: Some("MetadataEntry".to_string()),
                        field: vec![
                            FieldDescriptorProto {
                                name: Some("key".to_string()),
                                number: Some(1),
                                label: Some(FieldLabel::Optional),
                                r#type: Some(FieldType::String),
                                ..Default::default()
                            },
                            FieldDescriptorProto {
                                name: Some("value".to_string()),
                                number: Some(2),
                                label: Some(FieldLabel::Optional),
                                r#type: Some(FieldType::Int32),
                                ..Default::default()
                            },
                        ],
                        options: Some(MessageOptions {
                            map_entry: Some(true),
                            ..Default::default()
                        }),
                        ..Default::default()
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];
        assert!(source.contains("HashMap"));
        assert!(source.contains("#[prost(map"));
        // Map entry type should NOT generate a struct
        assert!(!source.contains("MetadataEntry"));
    }

    #[test]
    fn test_proto2_optional_and_required() {
        let fds = FileDescriptorSet {
            file: vec![FileDescriptorProto {
                name: Some("test.proto".to_string()),
                package: Some("test".to_string()),
                syntax: Some("proto2".to_string()),
                message_type: vec![DescriptorProto {
                    name: Some("Msg".to_string()),
                    field: vec![
                        FieldDescriptorProto {
                            name: Some("opt_field".to_string()),
                            number: Some(1),
                            label: Some(FieldLabel::Optional),
                            r#type: Some(FieldType::Int32),
                            ..Default::default()
                        },
                        FieldDescriptorProto {
                            name: Some("req_field".to_string()),
                            number: Some(2),
                            label: Some(FieldLabel::Required),
                            r#type: Some(FieldType::Int32),
                            ..Default::default()
                        },
                    ],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        };

        let result = generate_rust(&fds).unwrap();
        let source = &result["test.rs"];
        // Proto2 optional -> Option<i32>
        assert!(source.contains("pub opt_field: ::core::option::Option<i32>"));
        // Proto2 required -> bare i32
        assert!(source.contains("pub req_field: i32,"));
    }

    #[test]
    fn test_integration_with_analyzer() {
        let proto = r#"
            syntax = "proto3";
            package example;

            enum Color {
                COLOR_UNKNOWN = 0;
                COLOR_RED = 1;
                COLOR_GREEN = 2;
                COLOR_BLUE = 3;
            }

            message Person {
                string name = 1;
                int32 id = 2;
                repeated string emails = 3;
                Color favorite_color = 4;
            }
        "#;

        let fds = protoc_rs_analyzer::analyze(proto).unwrap();
        let result = generate_rust(&fds).unwrap();
        let source = &result["example.rs"];

        // Check enum
        assert!(source.contains("pub enum Color"));
        assert!(source.contains("Unknown = 0,"));
        assert!(source.contains("Red = 1,"));

        // Check message
        assert!(source.contains("pub struct Person"));
        assert!(source.contains("pub name: ::prost::alloc::string::String,"));
        assert!(source.contains("pub id: i32,"));
        assert!(source.contains("pub emails: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,"));
        assert!(source.contains("pub favorite_color: i32,"));
    }
}
