//! Pure Rust protobuf runtime library.
//!
//! This crate provides the runtime types and encoding/decoding primitives
//! for protobuf messages generated by protoc-rs. It replaces prost as the
//! runtime dependency, giving full control over wire format handling,
//! type-safe enums, cached serialization, and unknown field preservation.
//!
//! # Features
//!
//! - `std` (default) — use the standard library
//! - `json` — Proto3 JSON mapping via serde (requires `std`)
//!
//! # no_std
//!
//! Disable the default `std` feature for `no_std + alloc` environments:
//! ```toml
//! protoc-rs-runtime = { version = "0.1", default-features = false }
//! ```

#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(not(feature = "std"))]
extern crate alloc;

pub mod cached_size;
pub mod enumeration;
pub mod error;
pub mod extension;
pub mod message;
pub mod message_field;
pub mod unknown_fields;
pub mod view;
pub mod wire;

// Re-export key types at the crate root for convenience.
pub use cached_size::CachedSize;
pub use enumeration::{EnumValue, Enumeration};
pub use error::DecodeError;
pub use message::{decode, decode_with_options, encode, DecodeOptions, Message};
pub use message_field::{DefaultInstance, MessageField};
pub use unknown_fields::UnknownFields;
pub use view::{decode_view, MessageView};
pub use wire::WireType;
